/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiPenjualanTiketWisata;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class PenjualanTiket extends javax.swing.JFrame {
     
    DefaultTableModel model;
    
    /**
     * Creates new form PenjualanTiket
     * @throws java.sql.SQLException
     */
    public PenjualanTiket() throws SQLException {
        initComponents();
        String judul[] = {"Nama lengkap","Nomor identitas","Tanggal pemesanan","Jenis tiket","jumlah"};
        model = new DefaultTableModel(judul,0);
        tLaporanPesanan.setModel(model);
        tampilkan();           
    }
    
    private void tampilkan() throws SQLException{
        int row = tLaporanPesanan.getRowCount();
        for (int a=0;a<row;a++)
            model.removeRow(0);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/19630166_wisata", "root", "");
            ResultSet rs = con.createStatement().executeQuery("selecr * FROM tbl_pemesanan_tiket");
            while (rs.next()){
            String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
            model.addRow(data);
            }
        }catch (SQLException ex){
          Logger.getLogger(PenjualanTiket.class.getName()).log(Level.SEVERE, null, ex);
        }
                       
    }
    private void reset (){
        namalengkap.setText("");
        nomoridentitas.setText("");
        tanggalpemesanan.setText("");
        cbjbanyaktiket.setSelectedItem("");
        txthasilharga.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tanggalpemesanan = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tLaporanPesanan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namalengkap = new javax.swing.JTextField();
        nomoridentitas = new javax.swing.JTextField();
        cbjbanyaktiket = new javax.swing.JComboBox<>();
        txthasilharga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanggalpemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalpemesananActionPerformed(evt);
            }
        });
        jPanel1.add(tanggalpemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 280, 30));

        reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 100, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("PESAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 110, -1));

        tLaporanPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tLaporanPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLaporanPesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tLaporanPesanan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 520, 90));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("PEMESANAN TIKET PERJALANAN WISATA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TOUR & TRAVEL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("News706 BT", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Lengkap");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("News706 BT", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nomor Identitas (KTP/ID lainnya");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("News706 BT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Pemesanan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("News706 BT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("News706 BT", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis Tiket");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        namalengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namalengkapActionPerformed(evt);
            }
        });
        jPanel1.add(namalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 280, 30));
        jPanel1.add(nomoridentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 280, 30));

        cbjbanyaktiket.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbjbanyaktiket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAKET WISATA", "PAKET ZIAROH", "PAKET CHARTERBUS" }));
        cbjbanyaktiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjbanyaktiketActionPerformed(evt);
            }
        });
        jPanel1.add(cbjbanyaktiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, 30));
        jPanel1.add(txthasilharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 280, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("OKE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 70, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AplikasiPenjualanTiketWisata/large-bali-go-live-promosi-pariwisata-bali-era-digital1463644578.jpg"))); // NOI18N
        jLabel11.setIconTextGap(5);
        jLabel11.setInheritsPopupMenu(false);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namalengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namalengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namalengkapActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TampilanAwal q = new TampilanAwal();
        q.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbjbanyaktiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjbanyaktiketActionPerformed
       cbjbanyaktiket.addItem("PAKET WISATA");
       cbjbanyaktiket.addItem("PAKET ZIAROH");
       cbjbanyaktiket.addItem("PAKET CHARTERBUS");
    }//GEN-LAST:event_cbjbanyaktiketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String nama = namalengkap.getText();
        String id = nomoridentitas.getText();
        String tanggal = tanggalpemesanan.getText();
        String jenisTiket = (String) cbjbanyaktiket.getSelectedItem();
        String jumlah = txthasilharga.getText();
        
        
        JOptionPane.showMessageDialog(null,
                "Nama\t\t: " + nama
                + "\nNomor Identitas\t\t:" + id
                + "\nTanggal Pemesanan\t\t: " + tanggal
                +"\njumlah\t\t: " + jumlah
                +"\nJenis Tiket\t\t: " + jenisTiket
                
        );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tLaporanPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLaporanPesananMouseClicked
        int i = tLaporanPesanan.getSelectedRow();
        if (i >-1){
            namalengkap.setText(model.getValueAt(i,0).toString());
            nomoridentitas.setText(model.getValueAt(i,1).toString());
            tanggalpemesanan.setText(model.getValueAt(i,2).toString());
            txthasilharga.setText(model.getValueAt(i,3).toString());
            cbjbanyaktiket.setSelectedItem(model.getValueAt(i,4).toString());
            
          
        }
    }//GEN-LAST:event_tLaporanPesananMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/19630166_wisata","root","");
            con.createStatement().executeUpdate("insert into tbl_pemesanan_tiket values"+""
            + "('"+namalengkap.getText()+"','"+nomoridentitas.getText()+"',"
            + "'"+tanggalpemesanan.getText()+"','"+txthasilharga.getText()+","
            + "'"+cbjbanyaktiket.getSelectedItem()+"')");
      
            
        } catch (SQLException ex) {
            Logger.getLogger(PenjualanTiket.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/19630166_wisata","root","");
            con.createStatement().executeUpdate("delete * from tbl_pemesanan_tiket='"+namalengkap.getText()+"");
            tampilkan();
            reset();
            
        } catch (SQLException ex) {
            Logger.getLogger(PenjualanTiket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetActionPerformed

    private void tanggalpemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalpemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalpemesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new PenjualanTiket().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PenjualanTiket.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbjbanyaktiket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namalengkap;
    private javax.swing.JTextField nomoridentitas;
    private javax.swing.JButton reset;
    private javax.swing.JTable tLaporanPesanan;
    private javax.swing.JTextField tanggalpemesanan;
    private javax.swing.JTextField txthasilharga;
    // End of variables declaration//GEN-END:variables
}
